version: "3.9"

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -ptest"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - mysql_data:/var/lib/mysql

  mariadb:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: test
      MARIADB_DATABASE: test
      MARIADB_ROOT_HOST: "%"
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD-SHELL", "healthcheck.sh --connect --innodb_initialized"]
      interval: 12s
      timeout: 7s
      retries: 3
    volumes:
      - mariadb_data:/var/lib/mysql

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: typeorm-test-db
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    healthcheck:
      test:
        ["CMD-SHELL", "pg_isready -q -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  mysql_data:
  mariadb_data:
  postgres_data:
