name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Lint
        run: pnpm lint

  test:
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        database: [mysql, postgres, sqlite]
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: test
          MYSQL_DATABASE: test
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping -h 127.0.0.1 -ptest"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -q -d $${POSTGRES_DB} -U $${POSTGRES_USER}"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
    env:
      TEST_DB_TYPE: ${{ matrix.database }}
      TEST_MYSQL_HOST: 127.0.0.1
      TEST_MYSQL_PORT: 3306
      TEST_MYSQL_USER: root
      TEST_MYSQL_PASSWORD: test
      TEST_MYSQL_DATABASE: test
      TEST_POSTGRES_HOST: 127.0.0.1
      TEST_POSTGRES_PORT: 5432
      TEST_POSTGRES_USER: postgres
      TEST_POSTGRES_PASSWORD: test
      TEST_POSTGRES_DATABASE: test
      TEST_SQLITE_DATABASE: ':memory:'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run tests
        run: pnpm test
